spring:
  application:
    name: api-gateway

server:
  port: 9000git

  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://localhost:8081
          predicates:
            - Path=/books/**
          filters:
            - AddRequestHeader=Authorization, Bearer <your-token>
            - name: Retry
              args:
                retries: 3
                methods: GET
                statuses: 500, BAD_GATEWAY, SERVICE_UNAVAILABLE
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
management:
  endpoints:
    web:
      exposure:
        include: "*"
