spring:
  application:
    name: api-gateway

server:
  port: 9000

  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://localhost:8081
          predicates:
            - Path=/books/**
        - id: author-service
          uri: http://localhost:8081
          predicates:
            - Path=/authors/**

        - id: loan-service
          uri: http://localhost:8082
          predicates:
            - Path=/loans/**
